services:
  backend:
    image: backend
    container_name: backend-nodejs
    restart: always
    ports:
      - 8000:8000
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    environment:
      TZ: Asia/Kolkata
      # - MONGO_URI=mongodb://mongo-db:27017
    depends_on:
      - db
    # volumes:
    #   - backend:/app
  
  frontend: 
    image: frontend
    container_name: frontend-nextjs
    restart: always
    ports:
      - 3000:3000
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    environment:
      TZ: Asia/Kolkata
    depends_on:
      - backend